version: "3.8"
services:
  db:
    image: postgres:15-alpine
    container_name: gleis-db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - gleis-net
  frontend:
    build: ./frontend
    container_name: gleis-frontend
    restart: always
    environment:
      NEXT_PUBLIC_API_URL: http://overhauser0:8000/api
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "5675:3000"
    depends_on:
      - backend
    networks:
      - gleis-net

  backend:
    build: ./backend
    container_name: gleis-backend
    restart: always
    environment:
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
      NOTION_API_KEY: ${NOTION_API_KEY}
      NOTION_DATABASE_ID: ${NOTION_DATABASE_ID}
    volumes:
      - ./backend:/app # コードをマウント（ホットリロード用）
      - /app/node_modules # NASとの同期から除外（高速化）
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - gleis-net

networks:
  gleis-net:
    driver: bridge
